### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by GatesWang** [wiccawill420/sql-scratch-capstone-turn-in#1]
## Rubric Score
 
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 3 ​(Meets Expectations)
* _Comment(s):_ For Question 3, there is no query provided to support the answer. One example of an acceptable query would be 

Select question, 
(Count(question)* 100 / (Select Count(*) From survey)) as Percentage
From survey 
Group By question

 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4 ​(Exceeds Expectations)
* _Comment(s):_ All queries are correct. Though the answer to 6.1 is slightly confusing considering that SUM() was used in place of COUNT(). 

### Criteria 3: Query Formatting
* _Score Level:_ 4 ​(Exceeds Expectations)
* _Comment(s):_ The query formatting was beautifully done. For the most part the project was clean, correct, and easy to read. 
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4 ​(Exceeds Expectations)
* _Comment(s):_ The usage of all sql showcases strong mastery of taught concepts. Terminology in written answers is clear and concise. 

 ### Overall Score: {16}/16
Overall really good project. Using SUM() instead of COUNT() is easier, though slightly confusing. Still, it showcases good knowledge of the advantages of using certain aggregate functions over others.

**Comment by wiccawill420** [comment]
Thank you for reviewing my project. I had a lot of fun doing it. 

Question 3 specifically said to use an outside program to calculate those values. It would have been easy to calculate inside sql, but I was following the instructions. Sorry if I misunderstood. Please let me know if my score can be updated and/or the question can be updated. Thanks!
-William

--ORIGINAL QUESTION--
3. Using a spreadsheet program like Excel or Google Sheets, calculate the percentage of users who answer each question.:

Which question(s) of the quiz have a lower completion rates?

What do you think is the reason?

Add this finding to your presentation slides!

**Comment by GatesWang** [comment]
Hi, yes. That is reasonable. I will update your grade.

**Comment by wiccawill420** [comment]
Thank you! Have a great day :)
